# encoding: utf-8
require File.expand_path(File.dirname(__FILE__)) + '/../test_helper'

# This file is generated by the Ruby Holiday gem.
#
# Definitions loaded: data/gb.yaml
class RumbleDefinitionTests < Test::Unit::TestCase  # :nodoc:

  def test_rumble
    {Date.civil(2012,1,2) => 'New Year\'s Day',
     Date.civil(2012,3,19) => 'St. Patrick\'s Day',
     Date.civil(2012,4,9) => 'Easter Monday',
     Date.civil(2012,4,10) => 'Easter Tuesday',
     Date.civil(2012,5,7) => 'May Day',
     Date.civil(2012,7,12) => '12th of July',
     Date.civil(2012,7,13) => '13th of July',
     Date.civil(2012,12,25) => 'Christmas Day',
     Date.civil(2012,12,26) => 'Boxing Day'}.each do |date, name|
      assert_equal name, (Holidays.on(date, :rumble, :observed)[0] || {})[:name]
    end

    # assert_equal 'St. Patrick\'s Day', Date.civil(2008,3,17).holidays(:rumble, :informal)[0][:name]
    # 
    # assert_equal 'Christmas Day', Date.civil(2008,12,25).holidays(:rumble, :observed)[0][:name]
    # assert_equal 'Christmas Day', Date.civil(2009,12,25).holidays(:rumble, :observed)[0][:name]
    # assert_equal 'Christmas Day', Date.civil(2010,12,27).holidays(:rumble, :observed)[0][:name]
    # 
    # assert_equal 'Boxing Day', Date.civil(2008,12,26).holidays(:rumble, :observed)[0][:name]
    # assert_equal 'Boxing Day', Date.civil(2009,12,28).holidays(:rumble, :observed)[0][:name]
    # assert_equal 'Boxing Day', Date.civil(2010,12,28).holidays(:rumble, :observed)[0][:name]
    # 
    # [:rumble].each do |r|
    #   assert_equal 'Easter Monday', Date.civil(2008,3,24).holidays(r)[0][:name]
    #   assert_equal 'Bank Holiday', Date.civil(2008,8,25).holidays(r)[0][:name]
    # end
  end
end
