# encoding: utf-8
module Holidays
  # This file is generated by the Ruby Holidays gem.
  #
  # Definitions loaded: data/gb.yaml
  #
  # To use the definitions in this file, load it right after you load the 
  # Holiday gem:
  #
  #   require 'holidays'
  #   require 'holidays/gb'
  #
  # All the definitions are available at https://github.com/alexdunae/holidays
  module Rumble # :nodoc:
    def self.defined_regions
      [:rumble]
    end

    def self.holidays_by_month
      {
      0 => [{:function => lambda { |year| Holidays.easter(year)+1 }, :function_id => "easter(year)+1", :name => "Easter Monday", :regions => [:rumble]},
            {:function => lambda { |year| Holidays.easter(year)+2 }, :function_id => "easter(year)+2", :name => "Easter Tuesday", :regions => [:rumble]}],            
      1 => [{:mday => 1, :name => "New Year's Day", :regions => [:rumble], :observed => lambda { |date| Holidays.to_monday_if_weekend(date) }, :observed_id => "to_monday_if_weekend"}],
      3 => [{:mday => 17, :name => "St. Patrick's Day", :regions => [:rumble], :observed => lambda { |date| Holidays.to_monday_if_weekend(date) }, :observed_id => "to_monday_if_weekend"}],
      5 => [{:wday => 1, :week => 1, :name => "May Day", :regions => [:rumble], :observed => lambda { |date| Holidays.to_monday_if_weekend(date) }, :observed_id => "to_monday_if_weekend"}],
      7 => [{:mday => 12, :name => "12th of July", :regions => [:rumble], :observed => lambda { |date| Holidays.to_monday_if_weekend(date) }, :observed_id => "to_monday_if_weekend"},
            {:mday => 13, :name => "13th of July", :regions => [:rumble], :observed => lambda { |date| Holidays.to_monday_if_weekend(date) }, :observed_id => "to_monday_if_weekend"}],
      12 => [{:mday => 25, :observed => lambda { |date| Holidays.to_monday_if_weekend(date) }, :observed_id => "to_monday_if_weekend", :name => "Christmas Day", :regions => [:rumble]},
            {:mday => 26, :observed => lambda { |date| Holidays.to_weekday_if_boxing_weekend(date) }, :observed_id => "to_weekday_if_boxing_weekend", :name => "Boxing Day", :regions => [:rumble]}]
      }
    end
  end


end

Holidays.merge_defs(Holidays::Rumble.defined_regions, Holidays::Rumble.holidays_by_month)
